#!/bin/sh

cd infrastructure
echo "Running terraform fmt ..."
terraform fmt -recursive

echo "Running terraform validate ..."
terraform validate  # ❗ Eğer hata olursa script durur

echo "Running tflint ..."
tflint  # ❗ Eğer hata olursa script durur

echo "All Terraform checks passed."
cd ..

